apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm516-lembretes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lembretes
  template:
    metadata:
      labels:
        app: lembretes
    spec:
      containers:
        - name: lembretes
          image: rodbossini/ecm516-lembretes
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
              

